### PR TITLE
ic50 curve plot

### PR DESCRIPTION
**Pull request by rosherbal**

### CODE REVIEW

**Review by npalacioescat — CHANGES_REQUESTED** [review]
I personally try to keep figures text-free (e.g.: may be used for many purposes, labels are more usage-dependent). Very nice addition anyway, thanks :)

**Comment by rosherbal** [comment]
Good idea. I have removed the text and save it as plain svg

**Comment by rosherbal** [comment]
Good idea. I have removed the text and save it as plain svg

**Comment by rosherbal** [comment]
Good idea. I have removed the text and save it as plain svg.

**Comment by rosherbal** [comment]
Good idea. I have removed the text and save it as plain svg.

**Review by npalacioescat — APPROVED** [review]

**Pull request merged**
